FIND_PATH(ACCELERATE_FRAMEWORK_INCLUDE_DIR cblas.h /usr/include /usr/local/include
        /System/Library/Frameworks/vecLib.framework/Versions/A/Headers/ )

MARK_AS_ADVANCED(ACCELERATE_FRAMEWORK_INCLUDE_DIR)

SET( ACCELERATE_FRAMEWORK_LINK_FLAGS "-framework Accelerate" )

IF (ACCELERATE_FRAMEWORK_FOUND)
  IF (NOT ACCELERATE_FRAMEWORK_FIND_QUIETLY)
     MESSAGE(STATUS "Found ACCELERATE_FRAMEWORK: ${ACCELERATE_FRAMEWORK_INCLUDE_DIR}")
  ENDIF (NOT ACCELERATE_FRAMEWORK_FIND_QUIETLY)
ELSE(ACCELERATE_FRAMEWORK_FOUND)
  IF (ACCELERATE_FRAMEWORK_FIND_REQUIRED)
     MESSAGE(FATAL_ERROR "Could not find ACCELERATE_FRAMEWORK")
  ENDIF (ACCELERATE_FRAMEWORK_FIND_REQUIRED)
ENDIF (ACCELERATE_FRAMEWORK_FOUND)

