
FIND_PATH(LIBSNDFILE_INCLUDE_DIR sndfile.h)

SET(LIBSNDFILE_NAMES ${LIBSNDFILE_NAMES} sndfile libsndfile)
FIND_LIBRARY(LIBSNDFILE_LIBRARY NAMES ${LIBSNDFILE_NAMES} PATH)

IF(LIBSNDFILE_INCLUDE_DIR AND LIBSNDFILE_LIBRARY)
	SET(LIBSNDFILE_FOUND TRUE)
ENDIF(LIBSNDFILE_INCLUDE_DIR AND LIBSNDFILE_LIBRARY)

IF(LIBSNDFILE_FOUND)
	IF(NOT LIBSNDFILE_FIND_QUIETLY)
		MESSAGE(STATUS "Found libsndfile: ${LIBSNDFILE_LIBRARY}")
	ENDIF (NOT LIBSNDFILE_FIND_QUIETLY)
ELSE(LIBSNDFILE_FOUND)
	IF(LIBSNDFILE_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find libsndfile")
	ENDIF(LIBSNDFILE_FIND_REQUIRED)
ENDIF (LIBSNDFILE_FOUND)

